/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProjetoSlugRouteImport } from './routes/projeto.$slug'
import { Route as AdminTecnologiasRouteImport } from './routes/admin.tecnologias'
import { Route as AdminProjetosRouteImport } from './routes/admin.projetos'
import { Route as AdminMidiasRouteImport } from './routes/admin.midias'
import { Route as AdminGithubRouteImport } from './routes/admin.github'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProjetoSlugRoute = ProjetoSlugRouteImport.update({
  id: '/projeto/$slug',
  path: '/projeto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTecnologiasRoute = AdminTecnologiasRouteImport.update({
  id: '/tecnologias',
  path: '/tecnologias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjetosRoute = AdminProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMidiasRoute = AdminMidiasRouteImport.update({
  id: '/midias',
  path: '/midias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGithubRoute = AdminGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/github': typeof AdminGithubRoute
  '/admin/midias': typeof AdminMidiasRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/tecnologias': typeof AdminTecnologiasRoute
  '/projeto/$slug': typeof ProjetoSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/github': typeof AdminGithubRoute
  '/admin/midias': typeof AdminMidiasRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/tecnologias': typeof AdminTecnologiasRoute
  '/projeto/$slug': typeof ProjetoSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/github': typeof AdminGithubRoute
  '/admin/midias': typeof AdminMidiasRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/tecnologias': typeof AdminTecnologiasRoute
  '/projeto/$slug': typeof ProjetoSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/admin/configuracoes'
    | '/admin/github'
    | '/admin/midias'
    | '/admin/projetos'
    | '/admin/tecnologias'
    | '/projeto/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/admin/configuracoes'
    | '/admin/github'
    | '/admin/midias'
    | '/admin/projetos'
    | '/admin/tecnologias'
    | '/projeto/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/admin/configuracoes'
    | '/admin/github'
    | '/admin/midias'
    | '/admin/projetos'
    | '/admin/tecnologias'
    | '/projeto/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProjetoSlugRoute: typeof ProjetoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projeto/$slug': {
      id: '/projeto/$slug'
      path: '/projeto/$slug'
      fullPath: '/projeto/$slug'
      preLoaderRoute: typeof ProjetoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tecnologias': {
      id: '/admin/tecnologias'
      path: '/tecnologias'
      fullPath: '/admin/tecnologias'
      preLoaderRoute: typeof AdminTecnologiasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projetos': {
      id: '/admin/projetos'
      path: '/projetos'
      fullPath: '/admin/projetos'
      preLoaderRoute: typeof AdminProjetosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/midias': {
      id: '/admin/midias'
      path: '/midias'
      fullPath: '/admin/midias'
      preLoaderRoute: typeof AdminMidiasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/github': {
      id: '/admin/github'
      path: '/github'
      fullPath: '/admin/github'
      preLoaderRoute: typeof AdminGithubRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminGithubRoute: typeof AdminGithubRoute
  AdminMidiasRoute: typeof AdminMidiasRoute
  AdminProjetosRoute: typeof AdminProjetosRoute
  AdminTecnologiasRoute: typeof AdminTecnologiasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminGithubRoute: AdminGithubRoute,
  AdminMidiasRoute: AdminMidiasRoute,
  AdminProjetosRoute: AdminProjetosRoute,
  AdminTecnologiasRoute: AdminTecnologiasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProjetoSlugRoute: ProjetoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
